apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-avenue-api
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: sai-avenue-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sai-avenue-api
  template:
    metadata:
      labels:
        app: sai-avenue-api
    spec:
      containers:
        - name: sai-avenue-api
          image: musing.azurecr.io/sai-avenu-api:latest
          ports:
            - containerPort: 80
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: CONNECTION_STRING
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_AUDIENCE

---
apiVersion: v1
kind: Service
metadata:
  name: sai-avenue-api-service
spec:
  selector:
    app: sai-avenue-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer