name: Build and Deploy to Azure Web App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  AZURE_WEBAPP_NAME: MySocietyHub-api
  AZURE_RESOURCE_GROUP: MySocietyHub-test

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase image name
        run: |
          org_name=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "DOCKER_IMAGE=${org_name}/sai-avenue-api" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: SriSai.API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_ISSUER=${{ secrets.JWT_ISSUER }}
            JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEPLOY }}

      - name: Set image name
        run: |
          org_name=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "FULL_IMAGE_NAME=${{ env.REGISTRY }}/${org_name}/sai-avenue-api:latest" >> $GITHUB_ENV

      - name: Update container settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config container set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --docker-registry-server-url https://${{ env.REGISTRY }} \
              --docker-registry-server-user ${{ github.actor }} \
              --docker-registry-server-password ${{ secrets.GITHUB_TOKEN }} \
              --docker-custom-image-name ${{ env.FULL_IMAGE_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          images: ${{ env.FULL_IMAGE_NAME }}

      - name: Wait for deployment
        run: |
          sleep 30

      - name: Verify deployment and container status
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Checking container logs..."
            az webapp log tail \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

            echo "Checking container configuration..."
            az webapp config container show \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Restart web app
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Deployment status
        run: |
          echo "Deployment completed. Check the Azure Web App at https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
