name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: musing.azurecr.io
        username: ${{ secrets.AZURE_CR_USERNAME }}
        password: ${{ secrets.AZURE_CR_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
        docker buildx build --push \
          --tag musing.azurecr.io/sai-avenu-api:latest \
          --file Dockerfile .
