name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push \
            --tag ghcr.io/${{ github.repository_owner }}/sai-avenue-api:latest \
            --tag ghcr.io/${{ github.repository_owner }}/sai-avenue-api:${{ github.sha }} \
            --file SriSai.API/Dockerfile \
            --build-arg CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
            --build-arg JWT_AUDIENCE="${{ secrets.JWT_AUDIENCE }}" \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEPLOY }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name MySocietyHub-api \
            --resource-group MySocietyHub-test \
            --docker-custom-image-name ghcr.io/${{ github.repository_owner }}/sai-avenue-api:latest \
            --docker-registry-server-url https://ghcr.io \
            --docker-registry-server-user ${{ github.actor }} \
            --docker-registry-server-password ${{ secrets.GHCR_PAT }}

          az webapp restart \
            --name MySocietyHub-api \
            --resource-group MySocietyHub-test

      - name: Verify Deployment
        run: |
          echo "Deployment completed. Check the Azure Web App at https://mysocietyhub-test.azurewebsites.net"